name: Build Bazel Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Bazel (with caching)
      uses: bazel-contrib/setup-bazel@0.8.5
      with:
        bazelisk-cache: true               # Cache Bazelisk downloads
        disk-cache: ${{ github.workflow }}  # Store build cache per workflow
        repository-cache: true             # Share repository cache between workflows

    - name: Build with Bazel
      run: bazel build //app:main
      
